export enum WorkflowError {
  INVALID_TRANSITION = 'INVALID_TRANSITION',
  REVIEW_REQUIRED = 'REVIEW_REQUIRED',
  SUBMISSION_BLOCKED = 'SUBMISSION_BLOCKED',
  RECOVERY_FAILED = 'RECOVERY_FAILED',
  EDIT_LIMIT_EXCEEDED = 'EDIT_LIMIT_EXCEEDED'
}
