-- Create missing indexes
CREATE INDEX IF NOT EXISTS idx_citizen_createdat ON "Citizen"("createdAt");
CREATE INDEX IF NOT EXISTS idx_citizen_updated_at ON "Citizen"("updatedAt");
CREATE INDEX IF NOT EXISTS idx_complaint_createdat ON "Complaint"("createdAt");
CREATE INDEX IF NOT EXISTS idx_complaint_updatedat ON "Complaint"("updatedAt");
CREATE INDEX IF NOT EXISTS idx_charactercertificate_citizenid ON "CharacterCertificate"("citizenId");
CREATE INDEX IF NOT EXISTS idx_charactercertificate_createdat ON "CharacterCertificate"("createdAt");
CREATE INDEX IF NOT EXISTS idx_charactercertificate_updatedat ON "CharacterCertificate"("updatedAt");
CREATE INDEX IF NOT EXISTS idx_chathistory_sessionid ON "ChatHistory"("sessionId");
CREATE INDEX IF NOT EXISTS idx_chathistory_createdat ON "ChatHistory"("createdAt");
CREATE INDEX IF NOT EXISTS idx_knowledgeitem_createdat ON "KnowledgeItem"("createdAt");
CREATE INDEX IF NOT EXISTS idx_workflowsession_createdat ON "WorkflowSession"("createdAt");
CREATE INDEX IF NOT EXISTS idx_workflowsession_updatedat ON "WorkflowSession"("updatedAt");
CREATE INDEX IF NOT EXISTS idx_trackingrecord_citizenid ON "TrackingRecord"("citizenId");
CREATE INDEX IF NOT EXISTS idx_trackingrecord_createdat ON "TrackingRecord"("createdAt");
CREATE INDEX IF NOT EXISTS idx_trackingrecord_updatedat ON "TrackingRecord"("updatedAt");
CREATE INDEX IF NOT EXISTS idx_conversationinsight_sessionid ON "ConversationInsight"("sessionId");
CREATE INDEX IF NOT EXISTS idx_conversationinsight_citizenid ON "ConversationInsight"("citizenId");
CREATE INDEX IF NOT EXISTS idx_conversationinsight_createdat ON "ConversationInsight"("createdAt");
CREATE INDEX IF NOT EXISTS idx_intenttrainingdata_createdat ON "IntentTrainingData"("createdAt");
CREATE INDEX IF NOT EXISTS idx_workflowanalytics_createdat ON "WorkflowAnalytics"("createdAt");
CREATE INDEX IF NOT EXISTS idx_conversationsentiment_sessionid ON "ConversationSentiment"("sessionId");
CREATE INDEX IF NOT EXISTS idx_conversationsentiment_createdat ON "ConversationSentiment"("createdAt");
CREATE INDEX IF NOT EXISTS idx_unansweredquestion_createdat ON "UnansweredQuestion"("createdAt");
CREATE INDEX IF NOT EXISTS idx_policestation_createdat ON "PoliceStation"("createdAt");
CREATE INDEX IF NOT EXISTS idx_policestation_updatedat ON "PoliceStation"("updatedAt");
CREATE INDEX IF NOT EXISTS idx_learningevent_createdat ON "LearningEvent"("createdAt");
CREATE INDEX IF NOT EXISTS idx_aggregatedmetric_createdat ON "AggregatedMetric"("createdAt");
CREATE INDEX IF NOT EXISTS idx_jurisdictionregistryversion_createdat ON "JurisdictionRegistryVersion"("createdAt");
CREATE INDEX IF NOT EXISTS idx_jurisdictionmapping_createdat ON "JurisdictionMapping"("createdAt");
CREATE INDEX IF NOT EXISTS idx_jurisdictionmapping_updatedat ON "JurisdictionMapping"("updatedAt");
CREATE INDEX IF NOT EXISTS idx_jurisdictionresolutionevent_createdat ON "JurisdictionResolutionEvent"("createdAt");
CREATE INDEX IF NOT EXISTS idx_jurisdictionresolution_createdat ON "JurisdictionResolution"("createdAt");
CREATE INDEX IF NOT EXISTS idx_jurisdictionresolution_updatedat ON "JurisdictionResolution"("updatedAt");
CREATE INDEX IF NOT EXISTS idx_knowledgearticle_updatedat ON "KnowledgeArticle"("updatedAt");
CREATE INDEX IF NOT EXISTS idx_understandingterm_createdat ON "UnderstandingTerm"("createdAt");
CREATE INDEX IF NOT EXISTS idx_understandingcandidate_createdat ON "UnderstandingCandidate"("createdAt");
CREATE INDEX IF NOT EXISTS idx_situationassessmentsession_createdat ON "SituationAssessmentSession"("createdAt");
CREATE INDEX IF NOT EXISTS idx_situationassessmentsession_updatedat ON "SituationAssessmentSession"("updatedAt");
CREATE INDEX IF NOT EXISTS idx_complaintsession_createdat ON "ComplaintSession"("createdAt");
CREATE INDEX IF NOT EXISTS idx_complaintsession_updatedat ON "ComplaintSession"("updatedAt");
CREATE INDEX IF NOT EXISTS idx_understandingreviewqueue_createdat ON "UnderstandingReviewQueue"("createdAt");
CREATE INDEX IF NOT EXISTS idx_scenariographcandidate_createdat ON "ScenarioGraphCandidate"("createdAt");
CREATE INDEX IF NOT EXISTS idx_scenarioassessment_createdat ON "ScenarioAssessment"("createdAt");
CREATE INDEX IF NOT EXISTS idx_cuereplayresult_createdat ON "CueReplayResult"("createdAt");
CREATE INDEX IF NOT EXISTS idx_verification_citizenid ON "Verification"("citizenId");
CREATE INDEX IF NOT EXISTS idx_verification_createdat ON "Verification"("createdAt");
CREATE INDEX IF NOT EXISTS idx_verification_updatedat ON "Verification"("updatedAt");
CREATE INDEX IF NOT EXISTS idx_eventpermission_citizenid ON "EventPermission"("citizenId");
CREATE INDEX IF NOT EXISTS idx_eventpermission_createdat ON "EventPermission"("createdAt");
CREATE INDEX IF NOT EXISTS idx_eventpermission_updatedat ON "EventPermission"("updatedAt");
CREATE INDEX IF NOT EXISTS idx_citizenfeedback_sessionid ON "CitizenFeedback"("sessionId");
CREATE INDEX IF NOT EXISTS idx_scenariosession_createdat ON "ScenarioSession"("createdAt");
CREATE INDEX IF NOT EXISTS idx_scenariosession_updatedat ON "ScenarioSession"("updatedAt");
CREATE INDEX IF NOT EXISTS idx_notification_citizenid ON "Notification"("citizenId");
CREATE INDEX IF NOT EXISTS idx_notification_createdat ON "Notification"("createdAt");
CREATE INDEX IF NOT EXISTS idx_citizenpreference_createdat ON "CitizenPreference"("createdAt");

-- Extra custom composites/partials
CREATE INDEX IF NOT EXISTS idx_complaint_citizen_status ON "Complaint"("citizenId", "status");
CREATE INDEX IF NOT EXISTS idx_workflow_session_lookup ON "WorkflowSession"("citizenId", "serviceType", "isCompleted");

-- Drop redundant duplicate indexes
DROP INDEX IF EXISTS "idx_users_email";
DROP INDEX IF EXISTS "oauth_consents_active_user_client_idx";
DROP INDEX IF EXISTS "custom_oauth_providers_identifier_idx";
DROP INDEX IF EXISTS "idx_objects_bucket_id_name";
DROP INDEX IF EXISTS "SituationAssessmentSession_sessionId_idx";
DROP INDEX IF EXISTS "ComplaintSession_sessionId_idx";
