export type IncidentItemCode =
  | 'AADHAAR_CARD'
  | 'PAN_CARD'
  | 'DRIVING_LICENSE'
  | 'PASSPORT'
  | 'ATM_CARD'
  | 'DEBIT_CARD'
  | 'CREDIT_CARD'
  | 'MOBILE_PHONE'
  | 'CASH'
  | 'CHEQUEBOOK'
  | 'VEHICLE_RC'
  | 'UNKNOWN_DOCUMENT'
  | 'UNKNOWN_FINANCIAL'
  | 'UNKNOWN_DEVICE'
  | 'UNKNOWN_PROPERTY'
  | 'UNKNOWN_IDENTITY_DOCUMENTS'
  | 'UNKNOWN_BANK_CARDS'
  | 'UNKNOWN_ELECTRONICS'
  | 'UNKNOWN_OTHER';

export const SENSITIVE_ITEMS: IncidentItemCode[] = [
  'AADHAAR_CARD',
  'PAN_CARD',
  'PASSPORT',
  'ATM_CARD',
  'DEBIT_CARD',
  'CREDIT_CARD',
  'MOBILE_PHONE'
];

export const ITEM_RISK_SCORES: Record<IncidentItemCode, number> = {
  AADHAAR_CARD: 30,
  PAN_CARD: 30,
  DRIVING_LICENSE: 15,
  PASSPORT: 35,
  ATM_CARD: 40,
  DEBIT_CARD: 40,
  CREDIT_CARD: 40,
  MOBILE_PHONE: 25,
  CASH: 10,
  CHEQUEBOOK: 15,
  VEHICLE_RC: 20,
  UNKNOWN_DOCUMENT: 10,
  UNKNOWN_FINANCIAL: 15,
  UNKNOWN_DEVICE: 15,
  UNKNOWN_PROPERTY: 10,
  UNKNOWN_IDENTITY_DOCUMENTS: 10,
  UNKNOWN_BANK_CARDS: 15,
  UNKNOWN_ELECTRONICS: 15,
  UNKNOWN_OTHER: 5
};

export const RISK_TIERS = {
  LOW: [0, 20],
  MEDIUM: [21, 40],
  HIGH: [41, 70],
  CRITICAL: [71, Infinity]
};

export const ITEM_CATEGORIES: Record<IncidentItemCode, 'DOCUMENT' | 'FINANCIAL' | 'DEVICE' | 'GENERAL_LOST_PROPERTY' | 'OTHER' | 'UNKNOWN'> = {
  AADHAAR_CARD: 'DOCUMENT',
  PAN_CARD: 'DOCUMENT',
  DRIVING_LICENSE: 'DOCUMENT',
  PASSPORT: 'DOCUMENT',
  ATM_CARD: 'FINANCIAL',
  DEBIT_CARD: 'FINANCIAL',
  CREDIT_CARD: 'FINANCIAL',
  MOBILE_PHONE: 'DEVICE',
  CASH: 'GENERAL_LOST_PROPERTY',
  CHEQUEBOOK: 'FINANCIAL',
  VEHICLE_RC: 'DOCUMENT',
  UNKNOWN_DOCUMENT: 'DOCUMENT',
  UNKNOWN_FINANCIAL: 'FINANCIAL',
  UNKNOWN_DEVICE: 'DEVICE',
  UNKNOWN_PROPERTY: 'GENERAL_LOST_PROPERTY',
  UNKNOWN_IDENTITY_DOCUMENTS: 'DOCUMENT',
  UNKNOWN_BANK_CARDS: 'FINANCIAL',
  UNKNOWN_ELECTRONICS: 'DEVICE',
  UNKNOWN_OTHER: 'OTHER'
};

export const ITEM_DISPLAY_LABELS: Record<IncidentItemCode, string> = {
  AADHAAR_CARD: 'Aadhaar Card',
  PAN_CARD: 'PAN Card',
  DRIVING_LICENSE: 'Driving License',
  PASSPORT: 'Passport',
  ATM_CARD: 'ATM Card',
  DEBIT_CARD: 'Debit Card',
  CREDIT_CARD: 'Credit Card',
  MOBILE_PHONE: 'Mobile Phone',
  CASH: 'Cash',
  CHEQUEBOOK: 'Chequebook',
  VEHICLE_RC: 'Vehicle RC',
  UNKNOWN_DOCUMENT: 'Unknown Document',
  UNKNOWN_FINANCIAL: 'Unknown Financial Card/Document',
  UNKNOWN_DEVICE: 'Unknown Device',
  UNKNOWN_PROPERTY: 'Unknown Property',
  UNKNOWN_IDENTITY_DOCUMENTS: 'Unknown Documents Set',
  UNKNOWN_BANK_CARDS: 'Unknown Bank Cards Set',
  UNKNOWN_ELECTRONICS: 'Unknown Electronics Set',
  UNKNOWN_OTHER: 'Unknown Item'
};

export type OfficerAlertToken =
  | 'IDENTITY_THEFT_RISK'
  | 'FINANCIAL_FRAUD_RISK'
  | 'MULTIPLE_SENSITIVE_ITEMS'
  | 'DEVICE_AND_BANKING_COMBINATION'
  | 'FAMILY_DOCUMENT_INVOLVED'
  | 'MULTI_OWNER_INCIDENT'
  | 'POSSIBLE_IDENTITY_MISUSE'
  | 'DEVICE_IDENTITY_COMBINATION'
  | 'MULTI_FINANCIAL_EXPOSURE'
  | 'MULTIPLE_GOVERNMENT_DOCUMENTS';
