import { LocationRegistryItem } from './localization.types';

export const SUPPORTED_LANGUAGES = ['en', 'hi', 'hinglish'];

export const REVIEW_SECTIONS = {
  applicant: 'REVIEW_APPLICANT_PROFILE',
  subject: 'REVIEW_CANDIDATE_DETAILS',
  service: 'REVIEW_SERVICE_TYPE',
  validation: 'REVIEW_VALIDATION_STATUS',
  incident: 'REVIEW_INCIDENT_DETAILS',
  device: 'REVIEW_DEVICE_INFORMATION',
  ready: 'REVIEW_READY_FOR_SUBMISSION'
};

export const REVIEW_FIELDS = {
  name: 'REVIEW_CONTACT',
  mobile: 'REVIEW_CONTACT',
  address: 'REVIEW_ADDRESS',
  location: 'REVIEW_LOCATION',
  type: 'REVIEW_SERVICE_TYPE',
  deviceInfo: 'REVIEW_DEVICE_INFORMATION'
};

export const LocationRegistry: LocationRegistryItem[] = [
  // --- STATES & UNION TERRITORIES (36) ---
  { type: 'STATE', code: 'AP', en: 'Andhra Pradesh', hi: 'आंध्र प्रदेश', hinglish: 'Andhra Pradesh' },
  { type: 'STATE', code: 'AR', en: 'Arunachal Pradesh', hi: 'अरुणाचल प्रदेश', hinglish: 'Arunachal Pradesh' },
  { type: 'STATE', code: 'AS', en: 'Assam', hi: 'असम', hinglish: 'Assam' },
  { type: 'STATE', code: 'BR', en: 'Bihar', hi: 'बिहार', hinglish: 'Bihar' },
  { type: 'STATE', code: 'CG', en: 'Chhattisgarh', hi: 'छत्तीसगढ़', hinglish: 'Chhattisgarh' },
  { type: 'STATE', code: 'GA', en: 'Goa', hi: 'गोवा', hinglish: 'Goa' },
  { type: 'STATE', code: 'GJ', en: 'Gujarat', hi: 'गुजरात', hinglish: 'Gujarat' },
  { type: 'STATE', code: 'HR', en: 'Haryana', hi: 'हरियाणा', hinglish: 'Haryana' },
  { type: 'STATE', code: 'HP', en: 'Himachal Pradesh', hi: 'हिमाचल प्रदेश', hinglish: 'Himachal Pradesh' },
  { type: 'STATE', code: 'JH', en: 'Jharkhand', hi: 'झारखंड', hinglish: 'Jharkhand' },
  { type: 'STATE', code: 'KA', en: 'Karnataka', hi: 'कर्नाटक', hinglish: 'Karnataka' },
  { type: 'STATE', code: 'KL', en: 'Kerala', hi: 'केरल', hinglish: 'Kerala' },
  { type: 'STATE', code: 'MP', en: 'Madhya Pradesh', hi: 'मध्य प्रदेश', hinglish: 'Madhya Pradesh' },
  { type: 'STATE', code: 'MH', en: 'Maharashtra', hi: 'महाराष्ट्र', hinglish: 'Maharashtra' },
  { type: 'STATE', code: 'MN', en: 'Manipur', hi: 'मणिपुर', hinglish: 'Manipur' },
  { type: 'STATE', code: 'ML', en: 'Meghalaya', hi: 'मेघालय', hinglish: 'Meghalaya' },
  { type: 'STATE', code: 'MZ', en: 'Mizoram', hi: 'मिजोरम', hinglish: 'Mizoram' },
  { type: 'STATE', code: 'NL', en: 'Nagaland', hi: 'नागालैंड', hinglish: 'Nagaland' },
  { type: 'STATE', code: 'OD', en: 'Odisha', hi: 'ओडिशा', hinglish: 'Odisha' },
  { type: 'STATE', code: 'PB', en: 'Punjab', hi: 'पंजाब', hinglish: 'Punjab' },
  { type: 'STATE', code: 'RJ', en: 'Rajasthan', hi: 'राजस्थान', hinglish: 'Rajasthan' },
  { type: 'STATE', code: 'SK', en: 'Sikkim', hi: 'सिक्किम', hinglish: 'Sikkim' },
  { type: 'STATE', code: 'TN', en: 'Tamil Nadu', hi: 'तमिलनाडु', hinglish: 'Tamil Nadu' },
  { type: 'STATE', code: 'TG', en: 'Telangana', hi: 'तेलंगाना', hinglish: 'Telangana' },
  { type: 'STATE', code: 'TR', en: 'Tripura', hi: 'त्रिपुरा', hinglish: 'Tripura' },
  { type: 'STATE', code: 'UP', en: 'Uttar Pradesh', hi: 'उत्तर प्रदेश', hinglish: 'Uttar Pradesh' },
  { type: 'STATE', code: 'UK', en: 'Uttarakhand', hi: 'उत्तराखंड', hinglish: 'Uttarakhand' },
  { type: 'STATE', code: 'WB', en: 'West Bengal', hi: 'पश्चिम बंगाल', hinglish: 'West Bengal' },
  // Union Territories
  { type: 'STATE', code: 'AN', en: 'Andaman and Nicobar Islands', hi: 'अंडमान और निकोबार द्वीप समूह', hinglish: 'Andaman and Nicobar Islands' },
  { type: 'STATE', code: 'CH', en: 'Chandigarh', hi: 'चंडीगढ़', hinglish: 'Chandigarh' },
  { type: 'STATE', code: 'DN', en: 'Dadra and Nagar Haveli and Daman and Diu', hi: 'दादरा और नगर हवेली तथा दमन और दीव', hinglish: 'Dadra and Nagar Haveli and Daman and Diu' },
  { type: 'STATE', code: 'DL', en: 'Delhi', hi: 'दिल्ली', hinglish: 'Delhi' },
  { type: 'STATE', code: 'JK', en: 'Jammu and Kashmir', hi: 'जम्मू और कश्मीर', hinglish: 'Jammu and Kashmir' },
  { type: 'STATE', code: 'LA', en: 'Ladakh', hi: 'लद्दाख', hinglish: 'Ladakh' },
  { type: 'STATE', code: 'LD', en: 'Lakshadweep', hi: 'लक्षद्वीप', hinglish: 'Lakshadweep' },
  { type: 'STATE', code: 'PY', en: 'Puducherry', hi: 'पुदुचेरी', hinglish: 'Puducherry' },

  // --- UTTAR PRADESH DISTRICTS (75) ---
  { type: 'DISTRICT', code: 'AGRA', stateCode: 'UP', en: 'Agra', hi: 'आगरा', hinglish: 'Agra' },
  { type: 'DISTRICT', code: 'ALIGARH', stateCode: 'UP', en: 'Aligarh', hi: 'अलीगढ़', hinglish: 'Aligarh' },
  { type: 'DISTRICT', code: 'PRAYAGRAJ', stateCode: 'UP', en: 'Prayagraj', hi: 'प्रयागराज', hinglish: 'Prayagraj' },
  { type: 'DISTRICT', code: 'AMBEDKAR_NAGAR', stateCode: 'UP', en: 'Ambedkar Nagar', hi: 'अम्बेडकर नगर', hinglish: 'Ambedkar Nagar' },
  { type: 'DISTRICT', code: 'AMETHI', stateCode: 'UP', en: 'Amethi', hi: 'अमेठी', hinglish: 'Amethi' },
  { type: 'DISTRICT', code: 'AMROHA', stateCode: 'UP', en: 'Amroha', hi: 'अमरोहा', hinglish: 'Amroha' },
  { type: 'DISTRICT', code: 'AURAIYA', stateCode: 'UP', en: 'Auraiya', hi: 'औरैया', hinglish: 'Auraiya' },
  { type: 'DISTRICT', code: 'AZAMGARH', stateCode: 'UP', en: 'Azamgarh', hi: 'आज़मगढ़', hinglish: 'Azamgarh' },
  { type: 'DISTRICT', code: 'BAGHPAT', stateCode: 'UP', en: 'Baghpat', hi: 'बागपत', hinglish: 'Baghpat' },
  { type: 'DISTRICT', code: 'BAHRAICH', stateCode: 'UP', en: 'Bahraich', hi: 'बहराइच', hinglish: 'Bahraich' },
  { type: 'DISTRICT', code: 'BALLIA', stateCode: 'UP', en: 'Ballia', hi: 'बलिया', hinglish: 'Ballia' },
  { type: 'DISTRICT', code: 'BALRAMPUR', stateCode: 'UP', en: 'Balrampur', hi: 'बलरामपुर', hinglish: 'Balrampur' },
  { type: 'DISTRICT', code: 'BANDA', stateCode: 'UP', en: 'Banda', hi: 'बाँदा', hinglish: 'Banda' },
  { type: 'DISTRICT', code: 'BARABANKI', stateCode: 'UP', en: 'Barabanki', hi: 'बाराबंकी', hinglish: 'Barabanki' },
  { type: 'DISTRICT', code: 'BAREILLY', stateCode: 'UP', en: 'Bareilly', hi: 'बरेली', hinglish: 'Bareilly' },
  { type: 'DISTRICT', code: 'BASTI', stateCode: 'UP', en: 'Basti', hi: 'बस्ती', hinglish: 'Basti' },
  { type: 'DISTRICT', code: 'BHADOHI', stateCode: 'UP', en: 'Bhadohi', hi: 'भदोही', hinglish: 'Bhadohi' },
  { type: 'DISTRICT', code: 'BIJNOR', stateCode: 'UP', en: 'Bijnor', hi: 'बिजनौर', hinglish: 'Bijnor' },
  { type: 'DISTRICT', code: 'BUDAUN', stateCode: 'UP', en: 'Budaun', hi: 'बदायूँ', hinglish: 'Budaun' },
  { type: 'DISTRICT', code: 'BULANDSHAHR', stateCode: 'UP', en: 'Bulandshahr', hi: 'बुलंदशहर', hinglish: 'Bulandshahr' },
  { type: 'DISTRICT', code: 'CHANDAULI', stateCode: 'UP', en: 'Chandauli', hi: 'चंदौली', hinglish: 'Chandauli' },
  { type: 'DISTRICT', code: 'CHITRAKOOT', stateCode: 'UP', en: 'Chitrakoot', hi: 'चित्रकूट', hinglish: 'Chitrakoot' },
  { type: 'DISTRICT', code: 'DEORIA', stateCode: 'UP', en: 'Deoria', hi: 'देवरिया', hinglish: 'Deoria' },
  { type: 'DISTRICT', code: 'ETAH', stateCode: 'UP', en: 'Etah', hi: 'एटा', hinglish: 'Etah' },
  { type: 'DISTRICT', code: 'ETAWAH', stateCode: 'UP', en: 'Etawah', hi: 'इटावा', hinglish: 'Etawah' },
  { type: 'DISTRICT', code: 'AYODHYA', stateCode: 'UP', en: 'Ayodhya', hi: 'अयोध्या', hinglish: 'Ayodhya' },
  { type: 'DISTRICT', code: 'FARRUKHABAD', stateCode: 'UP', en: 'Farrukhabad', hi: 'फर्रुखाबाद', hinglish: 'Farrukhabad' },
  { type: 'DISTRICT', code: 'FATEHPUR', stateCode: 'UP', en: 'Fatehpur', hi: 'फतेहपुर', hinglish: 'Fatehpur' },
  { type: 'DISTRICT', code: 'FIROZABAD', stateCode: 'UP', en: 'Firozabad', hi: 'फिरोज़ाबाद', hinglish: 'Firozabad' },
  { type: 'DISTRICT', code: 'GAUTAM_BUDDHA_NAGAR', stateCode: 'UP', en: 'Gautam Buddha Nagar', hi: 'गौतम बुद्ध नगर', hinglish: 'Gautam Buddha Nagar' },
  { type: 'DISTRICT', code: 'GHAZIABAD', stateCode: 'UP', en: 'Ghaziabad', hi: 'गाजियाबाद', hinglish: 'Ghaziabad' },
  { type: 'DISTRICT', code: 'GHAZIPUR', stateCode: 'UP', en: 'Ghazipur', hi: 'गाज़ीपुर', hinglish: 'Ghazipur' },
  { type: 'DISTRICT', code: 'GONDA', stateCode: 'UP', en: 'Gonda', hi: 'गोंडा', hinglish: 'Gonda' },
  { type: 'DISTRICT', code: 'GORAKHPUR', stateCode: 'UP', en: 'Gorakhpur', hi: 'गोरखपुर', hinglish: 'Gorakhpur' },
  { type: 'DISTRICT', code: 'HAMIRPUR', stateCode: 'UP', en: 'Hamirpur', hi: 'हमीरपुर', hinglish: 'Hamirpur' },
  { type: 'DISTRICT', code: 'HAPUR', stateCode: 'UP', en: 'Hapur', hi: 'हापुड़', hinglish: 'Hapur' },
  { type: 'DISTRICT', code: 'HARDOI', stateCode: 'UP', en: 'Hardoi', hi: 'हरदोई', hinglish: 'Hardoi' },
  { type: 'DISTRICT', code: 'HATHRAS', stateCode: 'UP', en: 'Hathras', hi: 'हाथरस', hinglish: 'Hathras' },
  { type: 'DISTRICT', code: 'JALAUN', stateCode: 'UP', en: 'Jalaun', hi: 'जालौन', hinglish: 'Jalaun' },
  { type: 'DISTRICT', code: 'JAUNPUR', stateCode: 'UP', en: 'Jaunpur', hi: 'जौनपुर', hinglish: 'Jaunpur' },
  { type: 'DISTRICT', code: 'JHANSI', stateCode: 'UP', en: 'Jhansi', hi: 'झाँसी', hinglish: 'Jhansi' },
  { type: 'DISTRICT', code: 'KANNAUJ', stateCode: 'UP', en: 'Kannauj', hi: 'कन्नौज', hinglish: 'Kannauj' },
  { type: 'DISTRICT', code: 'KANPUR_DEHAT', stateCode: 'UP', en: 'Kanpur Dehat', hi: 'कानपुर देहात', hinglish: 'Kanpur Dehat' },
  { type: 'DISTRICT', code: 'KANPUR_NAGAR', stateCode: 'UP', en: 'Kanpur Nagar', hi: 'कानपुर नगर', hinglish: 'Kanpur Nagar' },
  { type: 'DISTRICT', code: 'KASGANJ', stateCode: 'UP', en: 'Kasganj', hi: 'कासगंज', hinglish: 'Kasganj' },
  { type: 'DISTRICT', code: 'KAUSHAMBI', stateCode: 'UP', en: 'Kaushambi', hi: 'कौशाम्बी', hinglish: 'Kaushambi' },
  { type: 'DISTRICT', code: 'LAKHIMPUR_KHERI', stateCode: 'UP', en: 'Lakhimpur Kheri', hi: 'लखीमपुर खीरी', hinglish: 'Lakhimpur Kheri' },
  { type: 'DISTRICT', code: 'KUSHINAGAR', stateCode: 'UP', en: 'Kushinagar', hi: 'कुशीनगर', hinglish: 'Kushinagar' },
  { type: 'DISTRICT', code: 'LALITPUR', stateCode: 'UP', en: 'Lalitpur', hi: 'ललितपुर', hinglish: 'Lalitpur' },
  { type: 'DISTRICT', code: 'LUCKNOW', stateCode: 'UP', en: 'Lucknow', hi: 'लखनऊ', hinglish: 'Lucknow' },
  { type: 'DISTRICT', code: 'MAHARAJGANJ', stateCode: 'UP', en: 'Maharajganj', hi: 'महराजगंज', hinglish: 'Maharajganj' },
  { type: 'DISTRICT', code: 'MAHOBA', stateCode: 'UP', en: 'Mahoba', hi: 'महोबा', hinglish: 'Mahoba' },
  { type: 'DISTRICT', code: 'MAINPURI', stateCode: 'UP', en: 'Mainpuri', hi: 'मैनपुरी', hinglish: 'Mainpuri' },
  { type: 'DISTRICT', code: 'MATHURA', stateCode: 'UP', en: 'Mathura', hi: 'मथुरा', hinglish: 'Mathura' },
  { type: 'DISTRICT', code: 'MAU', stateCode: 'UP', en: 'Mau', hi: 'मऊ', hinglish: 'Mau' },
  { type: 'DISTRICT', code: 'MEERUT', stateCode: 'UP', en: 'Meerut', hi: 'मेरठ', hinglish: 'Meerut' },
  { type: 'DISTRICT', code: 'MIRZAPUR', stateCode: 'UP', en: 'Mirzapur', hi: 'मिर्ज़ापुर', hinglish: 'Mirzapur' },
  { type: 'DISTRICT', code: 'MORADABAD', stateCode: 'UP', en: 'Moradabad', hi: 'मुरादाबाद', hinglish: 'Moradabad' },
  { type: 'DISTRICT', code: 'MUZAFFARNAGAR', stateCode: 'UP', en: 'Muzaffarnagar', hi: 'मुज़फ्फरनगर', hinglish: 'Muzaffarnagar' },
  { type: 'DISTRICT', code: 'PILIBHIT', stateCode: 'UP', en: 'Pilibhit', hi: 'पीलीभीत', hinglish: 'Pilibhit' },
  { type: 'DISTRICT', code: 'PRATAPGARH', stateCode: 'UP', en: 'Pratapgarh', hi: 'प्रतापगढ़', hinglish: 'Pratapgarh' },
  { type: 'DISTRICT', code: 'RAE_BARELI', stateCode: 'UP', en: 'Rae Bareli', hi: 'रायबरेली', hinglish: 'Rae Bareli' },
  { type: 'DISTRICT', code: 'RAMPUR', stateCode: 'UP', en: 'Rampur', hi: 'रामपुर', hinglish: 'Rampur' },
  { type: 'DISTRICT', code: 'SAHARANPUR', stateCode: 'UP', en: 'Saharanpur', hi: 'सहारनपुर', hinglish: 'Saharanpur' },
  { type: 'DISTRICT', code: 'SAMBHAL', stateCode: 'UP', en: 'Sambhal', hi: 'संभल', hinglish: 'Sambhal' },
  { type: 'DISTRICT', code: 'SANT_KABIR_NAGAR', stateCode: 'UP', en: 'Sant Kabir Nagar', hi: 'संत कबीर नगर', hinglish: 'Sant Kabir Nagar' },
  { type: 'DISTRICT', code: 'SHAHJAHANPUR', stateCode: 'UP', en: 'Shahjahanpur', hi: 'शाहजहाँपुर', hinglish: 'Shahjahanpur' },
  { type: 'DISTRICT', code: 'SHAMLI', stateCode: 'UP', en: 'Shamli', hi: 'शामली', hinglish: 'Shamli' },
  { type: 'DISTRICT', code: 'SHRAVASTI', stateCode: 'UP', en: 'Shravasti', hi: 'श्रावस्ती', hinglish: 'Shravasti' },
  { type: 'DISTRICT', code: 'SIDDHARTHNAGAR', stateCode: 'UP', en: 'Siddharthnagar', hi: 'सिद्धार्थनगर', hinglish: 'Siddharthnagar' },
  { type: 'DISTRICT', code: 'SITAPUR', stateCode: 'UP', en: 'Sitapur', hi: 'सीतापुर', hinglish: 'Sitapur' },
  { type: 'DISTRICT', code: 'SONBHADRA', stateCode: 'UP', en: 'Sonbhadra', hi: 'सोनभद्र', hinglish: 'Sonbhadra' },
  { type: 'DISTRICT', code: 'SULTANPUR', stateCode: 'UP', en: 'Sultanpur', hi: 'सुल्तानपुर', hinglish: 'Sultanpur' },
  { type: 'DISTRICT', code: 'UNNAO', stateCode: 'UP', en: 'Unnao', hi: 'उन्नाव', hinglish: 'Unnao' },
  { type: 'DISTRICT', code: 'VARANASI', stateCode: 'UP', en: 'Varanasi', hi: 'वाराणसी', hinglish: 'Varanasi' }
];
