export const SESSION_SCHEMA_VERSION = '2.8.5';
export const ITEM_CLARIFICATION_TIMEOUT_MINUTES = 1440; // 24 hours
export const MAX_ITEM_CLARIFICATIONS = 5;
export const MAX_INCIDENT_ITEMS = 20;
export const MAX_CONTAINERS = 3;
export const MAX_ITEM_LENGTH = 100;
export const MAX_ITEM_TEXT = 1000;
export const MAX_UNKNOWN_ITEMS = 3;
export const MAX_UNKNOWN_RATIO = 0.5;
export const MAX_ITEMS_PER_CONTAINER = 20;
export const MAX_PENDING_EVIDENCE = 10;
export const MAX_EVIDENCE_PER_ITEM = 5;
export const MAX_SESSION_JSON_SIZE = 81920; // 80KB
export const MAX_AMENDMENTS = 50;
export const MAX_CRITICAL_RECOMMENDATIONS = 5;
export const MAX_HIGH_RECOMMENDATIONS = 10;
export const MAX_LOW_RECOMMENDATIONS = 10;
export const MAX_DEBUG_LOGS = 50;
export const MIN_CONFIDENCE_AUTO_ACCEPT = 'HIGH';
